### ISSUE TITLE
What do we do if there are prepared statements?

### ISSUE THREAD

**Issue by eads** [nprapps/debates#37]
It seems we may get prepared statements for some of the upcoming fact-checks. How should we handle that, if at all?

**Comment by jjelosua** [comment]
If we are going to do the live transcription anyhow we could store the prepared statement in another document, or if we are really sure that the speech is going to be identical then we could forget about the live factcheck and go with the statement document.

**Comment by eads** [comment]
I liked your idea of putting the prepared statements into the doc in suggestion mode, then approving as they are said (and adjusting in case of variations from the script). Doesn't look like we'll get them this time around though.
