### ISSUE TITLE
Virtual DOM parsing errors should not fail so hard

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/debates#44]

**Comment by jjelosua** [comment]
<img width="1330" alt="screenshot 2017-01-11 19 01 35" src="https://cloud.githubusercontent.com/assets/1834051/21860317/701c515e-d830-11e6-97a5-3237a7065694.png">

**Comment by jjelosua** [comment]
I think it would be safe to mark this as closed by the try catch commit above
